### ISSUE TITLE
[Fix] 사용자 인증 디테일 수정

### ISSUE THREAD

**Issue by hgi4657** [I4-14/project#23]
**⭐ Issue : Fix**
사용자 인증 디테일 수정 (권한, 예외)

**Description**
매니저, 사용자 권한에 따른 접근 권한 설정 수정
공통 예외처리를 통한 예외처리 구현 수정
회원가입 및 로그인 시 매니저 권한 체크를 이용해 권한 변경

**Todo**
- [x] 접근 권한 설정
- [x] 예외처리 설정
- [x] 매니저 권한 변경
- [x] 사용자 인증 응답 형태 수정
