### ISSUE TITLE
[Feat] kanbanboard 수정, 삭제, 순서변경 구현

### ISSUE THREAD

**Issue by kyungtae42** [I4-14/project#34]
**⭐ Issue : Feature**
kanbanboard 수정, 삭제, 순서변경 구현

**Description**
kanbanboard에서 edit 버튼을 누르면 컬럼 수정과 삭제 버튼, 순서 변경하는 기능이 나오도록 구현

**Todo**
- [x] edit 버튼 누르면 컬럼 수정, 삭제버튼이 토글되도록 구현
- [x] edit 버튼 누르면 순서변경 버튼이 나오고 버튼을 누르면 순서변경하는 기능이 토글되도록 구현
- [x] edit 버튼은 매니저 계정으로 로그인해야만 화면에 출력되도록 구현

**Reference(Optional) **
참고 사항이 있다면 작성해주세요
